### ISSUE TITLE
fre-yamltools

### ISSUE THREAD

**Issue by bcc2761** [NOAA-GFDL/fre-cli#10]
[fms_yaml_tools](https://github.com/NOAA-GFDL/fms_yaml_tools)
How to incorporate these tools into the CLI and leave as independent apps?
fre yaml diag [convert](https://github.com/NOAA-GFDL/fms_yaml_tools/blob/main/fms_yaml_tools/diag_table/diag_table_to_yaml.py) diag_table_atmos
Maybe instead: fre yaml diag-[convert](https://github.com/NOAA-GFDL/fms_yaml_tools/blob/main/fms_yaml_tools/diag_table/diag_table_to_yaml.py) [diag_table_atmos option] 
fre yaml diag [convert](https://github.com/NOAA-GFDL/fms_yaml_tools/blob/main/fms_yaml_tools/diag_table/diag_table_to_yaml.py) diag_table_land
fre yaml diag [combine](https://github.com/NOAA-GFDL/fms_yaml_tools/blob/main/fms_yaml_tools/diag_table/diag_table_to_yaml.py) diag_table_atmos.yaml diag_table_land.yaml diag_table.yaml
fre yaml field convert field_table

for each 3 types: converting from table, combining with each other, validating
Why YAMLs? the why dictates the need for extra tooling
How efficiently can a user figure out/be told by YAML processing tools what history files will be written out, what variables are set in the YAML, etc? Are there any other properties that would be an explicit gain in functionality?

**Comment by ilaflott** [comment]
this appears solved as of https://github.com/NOAA-GFDL/fre-cli/tree/4e8419f0af9a194669ad19408012153ff9353f66/fre/yamltools
