### ISSUE TITLE
Use git tag for fre-cli versioning

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fre-cli#109]
https://github.com/jbweston/miniver

To save us from manually updating the version in setup.py.

**Comment by ilaflott** [comment]
To sum up discussion with @ceblanton today-

git tags will have the format `YYYY.#`, e.g. `2024.01`. When we decide to create a new git tag, e.g. `2024.02`, we wish for an approach to getting the version # *automatically updated* for publishing the conda package within github's CI/CD.

**Comment by ilaflott** [comment]
this issue has been addressed
