### ISSUE TITLE
fre pp tools for am5 pp starting

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fre-cli#11]
There's some existing tooling in the fre/canopy "frepp" wrapper script that would really prefer to be here:

https://gitlab.gfdl.noaa.gov/fre2/system-settings/-/blob/main/bin/frepp

Functionality there that could be standalone fre-cli tools (hopefully..):

1. fre pp checkout-template NAME

Checkout pp template, from https://gitlab.gfdl.noaa.gov/fre2/workflows/postprocessing.git, to ~/cylc-src/NAME. If the destination already exists, do nothing.

2. fre pp configure -x XML NAME

Analogous to Dana's "fre pp configure -y pp.yaml" but will use a Bronx XML.

3. fre pp play -t YYYY NAME

If ~/cylc-run/NAME does not exist, then "cylc install NAME" first.

If NAME is already running ("cylc scan" could show this), then trigger the postprocessing at that YYYY time, with "cylc trigger NAME YYYY".

If it's not running, then start it first ("cylc play NAME"), then trigger the pp at the YYYY time.

**Comment by ilaflott** [comment]
This seems more appropriate for `gitlab.gfdl.noaa.gov/fre2`- some who see this issue wont be able to contribute as they wont have access to pages behind GFDL's firewall.

Closing this issue- it seems largely addressed already anyways.
