### ISSUE TITLE
follow github community guidelines

### ISSUE THREAD

**Issue by ilaflott** [NOAA-GFDL/fre-cli#119]
https://github.com/NOAA-GFDL/fre-cli/community

in particular, PR templates would be helpful 
- [x] Description
- [x] README
- [ ] Code of conduct
- [x] Contributing
- [x] License
- [ ] Security policy
- [x] Issue templates
- [x] Pull request template
- [x] Repository admins accept content reports

**Comment by ceblanton** [comment]
Thanks! Great suggestion. Definitely, let's follow the github community guidelines. 5 out of 9 is a good start but let's go for  100% :)
