### ISSUE TITLE
Absorb fre-workflows/app/remap-pp-components --> fre pp remap... or fre cmor <subtool> ? 

### ISSUE THREAD

**Issue by ilaflott** [NOAA-GFDL/fre-cli#134]
**Is your feature request related to a problem? Please describe.**
we wish to have proper fre-cli access to remap-pp-components routines used within the python/FRE2 ecosystem. Currently, [`remap-pp-components` is a routine within `fre-workflows`](https://github.com/NOAA-GFDL/fre-workflows/tree/main/app/remap-pp-components). 

**Describe the solution you'd like**
this is less trivial than the other two tool-absorption issues, due to significant overlap with `fre/cmor/CMORmixer.py`

**Describe alternatives you've considered**

**Additional context**
 a lot of this has to do with making sure directory structure for postprocessing output is in a format that `fre-bronx` understood. This directory structure is important for producing CMIP-publishable model output. 

This issue should probably have it's description and desired solution updated as more information becomes available.

**Comment by ilaflott** [comment]
After more thought, really this should be worded like, "have fre-workflows/app/remap-pp-components call fre cmor".

Which also means this issue belongs in fre-workflows and development effort belongs there. thoughts?

**Comment by Ciheim** [comment]
Definitely seems more appropriate for the issue to be there @ilaflott

**Comment by ilaflott** [comment]
this will be addressed in fre-workflows here: https://github.com/NOAA-GFDL/fre-workflows/issues/38
