### ISSUE TITLE
Update schema.json file for validation for combined-[experiment].yaml

### ISSUE THREAD

**Issue by singhd789** [NOAA-GFDL/fre-cli#167]
**Is your feature request related to a problem? Please describe.**
The `combine-yamls` tool combined the model, compile, platform, and experiment yamls into one combined-[experiment].yaml. An updated schema.json is needed to validate this combined yaml file

**Describe the solution you'd like**
There are schema.json files for both fre make yamls and fre pp yamls here:
fre make yamls schema: https://github.com/NOAA-GFDL/fre-cli/blob/main/fre/make/gfdlfremake/schema.json
fre pp yamls schema: https://github.com/NOAA-GFDL/fre-cli/blob/main/fre/pp/schema.json

They will probably need to be tweaked a bit and combined into one schema.json since the information is in one combine.yaml now.

**Comment by singhd789** [comment]
Covered in PR #168

**Comment by ilaflott** [comment]
> Covered in PR #168

closing if this is covered
