### ISSUE TITLE
Priority: schema and README for fre make

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/fre-cli#187]
- [x] There needs to be an updated README for fre make
- [x] The schema needsto be moved to the schema repo and included as a submodule.  Cloning for fre-cli should be done recursively.  Any instructions should be updated

**Comment by singhd789** [comment]
Being addressed in this issue in `gfdl_msd_schemas` repo: https://github.com/NOAA-GFDL/gfdl_msd_schemas/issues/9
