### ISSUE TITLE
Deployment Secrets + Vision

### ISSUE THREAD

**Issue by bcc2761** [NOAA-GFDL/fre-cli#19]
~Workflow script uses $ANACONDA_USERNAME and $ANACONDA_PASSWORD GitHub secrets; ideally this should be the GFDL Channel's login info, but Chris or my login info may be stored for use for the time being.~

In regards to when the action is run, it is set right now to be called on PR (closed, opened, etc.). 

~~However, there is an issue regarding versions. If the current version is not being changed (i.e. 0.1.0 to 0.1.1), the current existing package in the Anaconda cloud gets removed and nothing is uploaded.~~

Additionally, the end goal is to move the deployment out of this repo itself, and into the GFDL conda-recipes repo...

**Comment by ceblanton** [comment]
ANACONDA_USERNAME and ANACONDA_PASSWORD repository secrets are added. How do we check that they work?

**Comment by bcc2761** [comment]
- GFDL Channel issue resolved, fixed with token
- Version control needs to be added
- Chris suggests:
1. Conda publish action to be triggered upon pushes to main branch only (done)
2. New Conda build action file to be triggered upon pull request for testing
3. Deployment upon tagged releases

**Comment by bcc2761** [comment]
Update 4/16: 
- The cronjob was working for a while, until suddenly #75 arose with conda installation errors. In the case of the cronjob, `conda install fre-cli` keeps installing an older version (fre-cli 0.1.2) instead of fre-cli 0.1.4. The cause of this issue remains unknown, but this issue does not occur on Gaea with a personal conda (version 24.1), or on lscamd50-d (AMD dev box, conda version 23). Source of issue my be incompatible dependencies/packages, but this is only my guess. May really just be a conda version issue

**Comment by ilaflott** [comment]
@ceblanton whats the status of this when you get a chance?

**Comment by bcc2761** [comment]
@ilaflott as of changing from `module load conda` to `module load miniforge`, this has been solved. The latest version is now installed, but there is a persisting issue relating to the scrontab to daily install when the version number isn't changed despite code changes. I was trying to find a solution for this for a long time but never succeeded in finding a way to grab a $GIT_TAG and incorporate it as the meta.yaml's conda package version number

**Comment by ilaflott** [comment]
solved according to @bcc2761, `$GIT_TAG` aspects are being addressed in versioning issues/PRs
