### ISSUE TITLE
Update frecatalog tool documentation

### ISSUE THREAD

**Issue by singhd789** [NOAA-GFDL/fre-cli#27]
Create a README that would include a list of data catalog tools developed/integrated. 
- includes what each tool does and how to use them.
- since data catalog tools are packaged, this will provide good base instructions for how to integrate other packaged tools into the FRE-CLI in the future

**Comment by ilaflott** [comment]
so reading this again, particularly the second bullet point, this is less about documenting `fre catalog` calls and more about doc'ing how to add a new tool/subtool. If that's true, i recommend [closing this issue](https://github.com/NOAA-GFDL/fre-cli/blob/main/CONTRIBUTING.md)

**Comment by singhd789** [comment]
@ilaflott You're right, thanks! I opened this so long ago for Bennett and Ciheim, from when data catalog things were getting put into the fre-cli. This was a reminder for documentation in general. I do think documentation/readme for each tool would be nice, which would include a quickstart of how to use them (if this is the direction we're going). Maybe we should rework the issue instead of closing

**Comment by singhd789** [comment]
Also not entirely sure how simple the process of this script is or if they'll be more catalog tools

**Comment by ilaflott** [comment]
I like the idea of an issue for READMEs! we could have a checklist in it for each tool category. As far as how simple catalogbuilder is/is not, we will at least have some documentation from the catalogbuilder repo to help us understand what that tool is up to.

As far as reworking/new issue goes, the default sort on github's issues is "new". So, perhaps we should close this one and open a new, cleaner issue for visibility's sake. There's also not too much in here!

**Comment by ilaflott** [comment]
forgot to add at the end of that- i will leave it up to you @singhd789 to decide to close or re-open. I gave my take!
