### ISSUE TITLE
Remove `fc` and `cc` as options in the platform.yaml

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/fre-cli#283]
**Is your feature request related to a problem? Please describe.**
Remove `fc` and `cc` as options in the platform.yaml as these are currently not used and there is not plan to use them

The schema will also need to be updated!

**Describe the solution you'd like**
Remove `fc` and `cc` as options in the platform.yaml

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by singhd789** [comment]
@uramirez8707 Thanks!

**Comment by rem1776** [comment]
@uramirez8707 I think we need these fields in the platform yaml, they need to be set for container builds and for any platforms that aren't gaea.

**Comment by singhd789** [comment]
@rem1776 If it's not too much/if you have it available, can you paste some lines where fc and cc would be used in the container build?
