### ISSUE TITLE
frecatalog.py suggested changes

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [NOAA-GFDL/fre-cli#36]
https://github.com/NOAA-GFDL/fre-cli/blob/main/fre/frecatalog/frecatalog.py#L8

it says get_intake_gfdl , the file in catalogbuilder is gen_intake_gfdl.py. Make this consistent. 

The shebang could use an update to use whatever python is in user environment.

So, use #!/usr/bin/env python instead of /usr/bin/python. 

help needs some help.

Usage: frecatalog.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  buildcatalog  - Execute fre catalog build

**Comment by ilaflott** [comment]
To close this issue:

add help descriptions in `frecatalog.py`, status: incomplete

add/update shebang in `frecatalog.py`, status: incomplete


Already done:

`get_intake_gfdl` --> `gen_intake_gfdl`, status: [complete](https://github.com/search?q=repo%3ANOAA-GFDL%2Ffre-cli%20get_intake_gfdl&type=code)

**Comment by aradhakrishnanGFDL** [comment]
@ilaflott yes likely resolved by others. 
heads up @ceblanton  - catalog builder will have some [overdue] changes in the pythonic interactions. This will impact fre-cli, and issues will be created when ready.

**Comment by ilaflott** [comment]
closing- resolved by others, see above comment!
