### ISSUE TITLE
Refactoring Vision

### ISSUE THREAD

**Issue by bcc2761** [NOAA-GFDL/fre-cli#45]
Want to incorporate use of classes and better importing habits.

https://click.palletsprojects.com/en/8.1.x/complex/

**Comment by cwhitlock-NOAA** [comment]
I would also like to add wrappers that strip decorators from some functions with the intent of making them easier to call from other python scripts, re: https://stackoverflow.com/questions/40091347/call-another-click-command-from-a-click-command

This is mostly relevant to a wrapper script for the fre-cli workflow as a whole, but might get used elsewhere

**Comment by cwhitlock-NOAA** [comment]
One new branch: 45.call.wo.decorators

**Comment by ilaflott** [comment]
OH the PR was abandoned, NOT the `45.call.wo.decorators` branch. re-linking. apologies for noise.
