### ISSUE TITLE
fre pp bronx

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fre-cli#53]
Wrapper tool for traditional Bronx XML usage

https://gitlab.gfdl.noaa.gov/fre2/system-settings/-/blob/main/bin/frepp?ref_type=heads

**Comment by ilaflott** [comment]
how does this differ from `fre/pp/configure_script_xml.py` ? or is this idea no longer relevant?

**Comment by ilaflott** [comment]
"wrapper tool" --> the wrapper @cwhitlock-NOAA has worked on?

or a dual-running wrapper like we used to have?

**Comment by ceblanton** [comment]
Thanks! This can be closed now. `fre pp wrapper` is exactly the functionality, yes. It works OK now and @cwhitlock-NOAA is making it more resilient.

If Bennett were around, I might ask (again, I'm sure), whether it's possible to make the fre-cli catagory call work without a subcommand. e.g.

fre pp -c YAML -e EXPNAME -p PLATFORM -t TARGET

whereas today we have the perfectly fine

fre pp wrapper -c YAML -e EXPNAME -p PLATFORM -t TARGET

**Comment by ilaflott** [comment]
i agree that a `fre pp` call would be nice- lets make that a sep issue for clarity! closing via #104
