### ISSUE TITLE
fre pp configure, updates needed

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fre-cli#56]
fre pp configure currently writes rose-suite.conf, app/regrid-xy/rose-app.conf, and app/remap-pp-components/rose-app.conf.

We want it instead to write rose-suite.conf and save itself to ~/cylc-src/NAME/pp.yaml

where NAME is <exp>__<platform>__<target>

**Comment by singhd789** [comment]
This copies the `pp.yaml` and creates the rose-suite-exp in the right `~/cylc-src` directory (from the checkout step). If in the pp.yaml, the remap and regrid rose configuration paths are defined, it will write their rose-apps in the `~/cylc-src/name/app/....` folders. If these paths are not defined, it won't write the rose-app.confs (for their eventual retirement)
