### ISSUE TITLE
`fre pp configure -y edits.yaml` schema issue

### ISSUE THREAD

**Issue by bcc2761** [NOAA-GFDL/fre-cli#6]
`fre pp configure -y edits.yaml`, which uses a function from /fre-cli/fre/frepp/config.py, is unable to run successfully unless the user is inside of the /fre-cli/fre/frepp directory, where schema.json is located. 

Line 23-24 in config.py:
**23    with open("schema.json") as s:
24        schema = json.load(s)**

This can be fixed by adding a path like **with open("/home/Bennett.Chang/Coding/fre-cli/fre/frepp/schema.json") as s:**, but this will not work with users who aren't developers. Will they have their own clone of the fre-cli directory? Or will we have to locate their schema.json elsewhere (which can be tricky because everyone has their own paths)?

**Comment by ceblanton** [comment]
Yes, I think we need to include the schema.json file in the conda packaging so it will be available in a known location for all users.
