### ISSUE TITLE
History of Conda Issues

### ISSUE THREAD

**Issue by bcc2761** [NOAA-GFDL/fre-cli#75]
- ~~install issues, fixed with `conda config --append channels noaa-gfdl`~~
- ~~new tool implementations not being reflected in workflow runs and not recognizing new subtool modules, fixed with removing `git_url:` specifier in meta.yaml~~
- conda installation being killed for unknown reason, [reference](https://github.com/conda/conda/issues/9728)
    - potential fix idea suggest: adding more RAM, [this](https://stackoverflow.com/a/67454782/10270590), or from my experimenting, upgrading /app/conda/miniconda within workstation systems to be a higher version (versions 23+ are able to install fre-cli faster and without issues)

**Comment by ilaflott** [comment]
The only time i've seen this be a problem is if the `conda` version being used is of the `4.X.Y` variety. closing.
